server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false # 多台注册中心进行服务同步
    register-with-eureka: false
    region: local # 一般可以认为region 就是分布式的地理 比如北京地区 ，上海地区
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    availability-zones:
      local: defaultZone # zone 可以代表不同地理位置的机房 ，
