management:
  endpoints:
    web:
      base-path: /author # 使用这个方式修改监控上下文
eureka:
  instance:
    instance:
      health-check-url-path: ${management.endpoints.web.base-path}/health
      status-page-url-path: ${management.endpoints.web.base-path}/info # 相对路径配置
    hostname: localhost
    metadata-map:
      zone: defaultZone  #通过 这个 配置 过滤 同一个zone
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: true
    prefer-same-zone-eureka: true
    region: local
    availability-zones:
      local: defaultZone # 注意这个zone 配置需要用逗号分割
spring:
  application:
    name: api
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update # 数据库的操作模式
    show-sql: false # 是否在控制台打印SQL语句
    properties:
      hibernate:
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: false
  aop:
    auto: true
    proxy-target-class: true # 默认设置为false,使用的是标准Java动态代理的实现（接口），而不是cglib（类）
  datasource:
    sql-script-encoding: utf-8 # 解决中文乱码
    url: jdbc:postgresql://121.36.202.6:5432/TEST_SPRING_CLOUD?currentSchema=public
    username: xupp
    password: pass
    driver-class-name: org.postgresql.Driver
    maxActive: 200
    initialSize: 10
    minIdle: 10
    maxWait: 60000
    testWhileIdle: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: false
    minEvictableIdleTimeMillis: 60000
    timeBetweenEvictionRunsMillis: 60000
    testOnBorrow: false
    #validationQuery: select 1 from dual
    validationQuery: select version();
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 200
    #monitor: true # 是否启用数据库连接池监控，开启后损失部分性能
    #filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
web:
  static:
    url: http://121.36.202.6:8099/share/server-image
    imgdir: /usr/local/tomcat/apache-tomcat-8.5.46/webapps/share/server-image
storage:
  #  jcsjdirs: 测试目录1,测试目录2,测试目录3
  type: mongo # 默认启用文服务类型
  convertor: #文件预览配置
    type: KKFILEVIEW #默认使用 jacob进行文件的 预览
    environment: office # 本机使用的office产品
    server: http://127.0.0.1:8012/ #如果使用 office 其他服务端帮助转换返回地址 请配置服务端地址
  oss:
    endpoint: http://oss-cn-shanghai.aliyuncs.com #文件服务节点
    accessKeyId: LTAI4FtzjQniwH44W4z31LY7 #ak
    accessKeySecret: Y2EdnLiy9ZyHJ1uJgQ0iEe8ZphrUOA #sk
    bucketName: ghxt-oss # 命名空间
  mongo:
    host: 127.0.0.1 # 服务器地址
    port: 27017 # 对应的Mongo 监听端口
    database: fs
    collection: ghxt-mongo # 默认的存储集合
    auth: # 是否开启用户验证的方式
      enable: false #是否开启用户验证
      username: useroms #配置授权用户对应的用户名称
      password: Passw0rd #配置授权用户对应的用户密码
      database: admin  #认证用户存放的数据库位置